### API
GET http://localhost:3000/

### Listar produtos
GET http://localhost:3000/produtos

### Buscar produto por ID
GET http://localhost:3000/produtos/2

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "professor@teste.com",
  "senha": "123456"
}

### Validar token
# Cole abaixo o token obtido no login.
GET http://localhost:3000/auth/validar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJwcm9mZXNzb3JAdGVzdGUuY29tIiwiaWF0IjoxNzg5MjIyMTY0LCJleHAiOjE3ODkyMjU3NjR9.cXBQFpS1jvNCR5ydrFWBJfbXfG6z5UwlKCFOGOFfc6U

### Criar produto
POST http://localhost:3000/produtos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJwcm9mZXNzb3JAdGVzdGUuY29tIiwiaWF0IjoxNzg5MjIyMTY0LCJleHAiOjE3ODkyMjU3NjR9.cXBQFpS1jvNCR5ydrFWBJfbXfG6z5UwlKCFOGOFfc6U

{
  "descricao": "Mouse sem fio",
  "preco": 89.90,
  "categoria": "Periféricos",
  "estoque": 20
}

### Atualizar produto
PUT http://localhost:3000/produtos/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJwcm9mZXNzb3JAdGVzdGUuY29tIiwiaWF0IjoxNzg5MjIyMTY0LCJleHAiOjE3ODkyMjU3NjR9.cXBQFpS1jvNCR5ydrFWBJfbXfG6z5UwlKCFOGOFfc6U

{
  "preco": 99.90,
  "estoque": 15
}

### Excluir produto
DELETE http://localhost:3000/produtos/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJwcm9mZXNzb3JAdGVzdGUuY29tIiwiaWF0IjoxNzg5MjIyMTY0LCJleHAiOjE3ODkyMjU3NjR9.cXBQFpS1jvNCR5ydrFWBJfbXfG6z5UwlKCFOGOFfc6U
